### ISSUE TITLE
Alternative File Extension for TiddlyWiki Files

### ISSUE THREAD

**Issue by AnthonyMuscio** [ibnishak/Timimi#17]
Riz,

I believe we discussed this previously, but I hope to persuade you to take account of this in Timimi, I expect it to be a minor change with extensive benefits. I am trying to persuade all stakeholders.

Please consider my TiddlyWiki issue [Alternative File Extension for TiddlyWiki Files #3719](https://github.com/Jermolene/TiddlyWiki5/issues/3719)

PS I am currently asking BTC, TiddlyDesktop, TiddlyServer, Bob and Tiddlywiki itself to account for .tw files

Regards
Tony

**Comment by ibnishak** [comment]
We will visit this issue once Jeremy gives go ahead in tiddlydesktop. If it is not officially supported, and we implement it in Timimi, it will be considered a burden to be borne by users rather than a feature.

**Comment by AnthonyMuscio** [comment]
I respect your view, but I do not think it much of a burden at all, unless someone tries and use or rename a file to .tw they would not know it exists.

In fact Timimi already opens a .tw file eg file:///C:/Data/TW5/Development/empty.tw with a browser association, and recognises it as a TiddlyWiki, it "saves" the wiki including in backups with the correct extension. This is so versatile we could use additional extensions feely.

Same for htm files as well. That suggests to me Timimi need no change at all, perhaps only accept that such files exist and the should be treated the same as tiddlywiki.html files should you make any changes that this is relevant to.

I can download empty from TiddlyWiki and save as *.tw and it works with Timimi (others to be tested)

Regards
Tony

**Comment by ibnishak** [comment]
As far as this issue is considered, there is nothing to be remaining to be done on my part. As you pointed out, timimi does not care about the extension. Timimi only cares if the file is local and if the file is a tiddlywiki. If both turns true, it will save the file irrespective of the extension. 

That being the case, I am closing the issue for now. We will continue the discussion about official support for such extensions in the tiddlywiki repo.
