### ISSUE TITLE
Support of TiddlyWiki Classic

### ISSUE THREAD

**Issue by YakovL** [ibnishak/Timimi#23]
Hello Rizwan,

Recently I've successfully [adapted](https://groups.google.com/forum/#!topic/tiddlywikiclassic/TCuPSb2uMfQ) Timimi to TiddlyWiki Classic via a plugin and would like to suggest changes so that Timimi works with TWC without a plugin. However, before creating a PR, I'd like to test it myself.

To do so, I need to figure out how to build-install-test an updated code/extension. Could you point me a direction on this? I wonder if I can build the extension and install it into FireFox without verifying and uploading it to the store, is that possible?

Best regards,
Yakov.

**Comment by ibnishak** [comment]
Yes, definitely. The instructions are given in here
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Getting_started_with_web-ext

**Comment by YakovL** [comment]
Hi Rizwan, have you reviewed the PR? Any estimations when this update can make it into the extension?

**Comment by ibnishak** [comment]
I ll need to test it a little more extensively, I am afraid.

**Comment by YakovL** [comment]
Hi, I wonder (since I may help with that) whether you are talking about regression testing or new feature testing. For TW5 there should be no difference after applying the patch:

* patch-classic-io.js is injected for TWC only
* the only thing that could possible change something for TW5 is that I moved the call of `checkTW` a bit higher, but that actually shouldn't affect anything either, because "Loading settings from browser storage" and `checkTW` don't rely on each other; you can still revert that bit if it doesn't fit some ideas about further extending the web ext.

As for testing with TWC, I'm building a consistent set of tests and there'll be other changes in patch-classic-io.js (loading doesn't work correctly with non-ASCII paths, both loading and saving should accept callbacks, Timimi backups should be supported etc – it's just I took implementation from TiddlyFox and put here with minimal adaptation to get a minimal viable product in context of TWC)

**Comment by PengjuYan** [comment]
Hi Yakov,

I'm a quite heavy TWC user and I'll use it everyday. I've been using savetiddlers 0.6 version to save and back my TWC work. Yes, the latest version 0.8 of savetiddlers simply dosn't work for TWC! I fixed some bugs (other than the following one) in savetiddlers but haven't finished making it work. Last week, after the latest FireFox version 68 rolled out, even savetiddlers 0.6 doesn't work now. The reason behind it is that asynchronous XMLHttpRequest.open() in doesn't work any longer.

```
var injectedLoadFile = function (path) {
    try {
        // Just the read the file synchronously
        var xhReq = new XMLHttpRequest();
        xhReq.open("GET", "file:///" + escape(path), false);
        xhReq.send(null);
        return xhReq.responseText;
    } catch (e) { // alert(document.getElementById("contentWrapper"))
        return false;
    }
};
```

I developed my own add-on based on savetiddlers and it worked perfectly for TWC when I debugged it using "web-ext run". Then I uploaded the add-on to AMO and got approved. While I installed the signed xpi on my FireFox, I found that it didn't work (the issue above)! It seems that there are difference between "normal FireFox" and "web-ext FireFox".

Now the only way I can work on my TWC is to use "web-ext run" with my own add-on. It doesn't make much sense considering that I always to open external links to a "normal FireFox" tab. But for me it seems the only way.

I came across some discussion and found that you are working to add TWC support for Timimi. I'm looking forward to your progress. I guess many TWC users will be very happy with it.

Pengju

**Comment by ibnishak** [comment]
@YakovL  and @PengjuYan , the PR is merged and updated add-on can be installed from [firefox addons page](https://addons.mozilla.org/en-US/firefox/addon/timimi/). If you are installing the addon for the first time ever, make sure you follow instructions from [documentation](https://ibnishak.github.io/Timimi/#Installing%20Timimi) closely. Otherwise one may just need to update the timimi extension in browser

**Comment by PengjuYan** [comment]
@YakovL @ibnishak Thank you both very much for this amazing work! I guess many people like me will like this plugin because their TWC work will be saved.

I tested it for my TWC and it works pretty well and it can save my work anywhere (not only in the system downloads directory).

There're some minor problems (Not a bit deal though. I may be a little bit picky.) and I'll report it.

**Comment by YakovL** [comment]
By the way, @PengjuYan are you aware of the [TiddlyWiki Classic google group](https://groups.google.com/forum/#!forum/tiddlywikiclassic)? There are dedicated threads about saving where your contribution will be helpful (I personally haven't tested SaveTiddlers and it would be interesting to see your adaptation; but also there should be a standart for developing the savers in a "cross-TW-version" way which is [rather slowly] discussed [here](https://groups.google.com/forum/#!topic/tiddlywikidev/e8hAHYLWUbQ)).

**Comment by PengjuYan** [comment]
Thank you about pointing me to the 2 google groups. Actually what I did is to remove the same name checking (a bit difficult to explain) from savetiddlers which in some corner case will stop saving and cause losing of our work. I just don't want to discuss about my work (since it doesn't work for FireFox 68.0.1 neither) at present...

BTW, I posted another thread talking about my thoughts about asynchronous saving TWC: [Is it a good idea to save asynchronously?](https://groups.google.com/forum/#!topic/tiddlywikidev/0XbHgZks9OM).
