### ISSUE TITLE
No warning if it can't save

### ISSUE THREAD

**Issue by emarsk** [ibnishak/Timimi#31]
Currently, if for some reason Timimi fails to save the tiddlywiki, it doesn't give any warning: "Saved wiki" is displayed as if working correctly, even if it's not.

**Comment by YakovL** [comment]
Yeah, this week I've figured that the error handling should be done [here](https://github.com/ibnishak/Timimi/blob/master/addon-firefox/content-script.js#L134) and the handling itself should be done by either dispatching the `tiddlyfox-have-saved-file` event with params indicating that it failed, which would be semantically wrong but may be backward-compatible with current TW5 core; or by dispatching another event, [presumably](https://groups.google.com/forum/#!topic/tiddlywikidev/e8hAHYLWUbQ) `tiddlyfox-have-failed-to-save-file` and processing by TW core. For TWC, situation is a bit different since the reporting bit not passed as a callback to [JS](https://github.com/ibnishak/Timimi/blob/master/addon-firefox/patch-classic-io.js) injected by Timimi. My plan is to update TWC core first and propose an update of Timimi afterwards.

**Comment by ibnishak** [comment]
Timimi version 2.1 shows system notifications if there is an error in saving.  Please see.

**Comment by YakovL** [comment]
Hi Riz, this is also a great improvement, thanks for this!
