### ISSUE TITLE
When can it work on Chrome?

### ISSUE THREAD

**Issue by platoer** [ibnishak/Timimi#32]
like Chrome：）

**Comment by YakovL** [comment]
when somebody implements that :) I tried to adapt Timimi for Chrome and fixed several issues but stumbled upon one which I'm not sure how to debug (`Unchecked runtime.lastError: The message port closed before a response was received`), so haven't created any PR yet

**Comment by ibnishak** [comment]
It now works on Chrome, Chromium, Opera, Edge and Firefox. See Release 2.1

**Comment by YakovL** [comment]
Hi Riz, this is awesome news! Like I expected, saving in Chrome+ doesn't work with TWC and probably requires changing TWC core, so I'll take a look later. Thanks for this update!

One note, though: with this release, I've got weird behavior like browser tries to cache TW and although saving works, reloading sometimes shows the version before the last save. I'll create an issue once I understand how reproducible this is, but you can experiment a bit yourself.

**Comment by ibnishak** [comment]
@YakovL Hi
I was taking a look at the TWC save issue in chrome. So the mozillaLoadFile and mozillaSaveFile - are they events defined within TWC core? Are they bound to Firefox browser?

Would you like to open a separate ticket for this? I will help whatever way I can.

**Comment by YakovL** [comment]
`mozillaLoadFile` and `mozillaSaveFile` are js functions that are defined in TWC that were used when Firefox was able to save changes to file system by itself. Like in TiddlyFox, the adjustments in Timimi that I've proposed include overwriting these functions.

In Chrome, however, restrictions are stronger and extension code has no direct access to the page JS so the functions can not be modified this way. I have to re-read some stuff to tell confidently, but as far as I understand, saving TWC in Chrome can only be implemented after modifying its core.

I'll create another issue so that there's a place to collect info.
