### ISSUE TITLE
Upgrading to Mac OS Catalina gives security error for Timimi

### ISSUE THREAD

**Issue by bnash** [ibnishak/Timimi#40]
I recently [upgraded my MacOS](https://en.wikipedia.org/wiki/MacOS#Release_history) from HighSierra to Catalina, skipping over Mojave.

I have been using Timimi for awhile to save my tiddlywiki file changes and it has been working perfectly for me.

Unfortunately, after this change, it gave an error when I tried to save:

> "timimi" cannot be opened because the developer cannot be verified.
![timimiError](https://user-images.githubusercontent.com/1112276/79071441-02616800-7c99-11ea-8242-9c93e8b2a16f.png)

A brief effort to resolve this issue was unsuccessful, and I am not yet able to use Timimi again for saving.

**Comment by YakovL** [comment]
May be something from here will be useful: https://github.com/hashicorp/terraform/issues/23033
(I don't have an access to a mac currently, so can't try anything myself)
As far as I understand, the problem is with the native app (and not with the extension)
Riz, do you know anything about this developer verification thing?

**Comment by ibnishak** [comment]
I do not know about such an issue. Since I don't have access to an updated MacOS Catalina, I cannot give a complete reply to the same. If interested in trying out the same steps, timimi executable in Mac is located in `Library/Application Support/Mozilla/NativeMessagingHosts`.

Sans testing it out myself, I cannot guarantee it to work. I am sorry about that.

**Comment by bnash** [comment]
Thank you @YakovL and @ibnishak!
Your two comments together solved the problem!
Locating the executable and opening it to create an exception to the security issue allows timimi to be used from Firefox.
Glad to be able to use tiddlywiki again on my work computer!

**Comment by YakovL** [comment]
Hi, great, I think it will be nice if you share this solution in the initial thread in the Google Group.

@ibnishak , this may be worth mentioning in the installation instructions.

**Comment by bnash** [comment]
Message to Google group sent.
Regards,
Boaz

**Comment by ibnishak** [comment]
@bnash : Please note that from version 2.1 [latest] onwards, the executable can be located in `Library/Application Support/timimi/` 

This is to ensure that multiple browsers can access it. Please update and take necessary actions. 

@YakovL :+1:  I will definitely update the info in docs
