### ISSUE TITLE
Can't save anymore...

### ISSUE THREAD

**Issue by bloff** [ibnishak/Timimi#50]
I am getting this weird error message and there was nothing on it in the internet.

When I try to save a wiki, I get the message:

As your TW is not within the contolled directory a manual save is required

And then it prompts me to the "save to" dialog.

A screenshot is attached.

![Screenshot from 2020-06-15 10-56-13](https://user-images.githubusercontent.com/3836039/84644439-16268600-aef7-11ea-9c8e-1546cfc0a4d5.png)

**Comment by ibnishak** [comment]
Does the issue persist when you try to save from any other folder? OS and Browser?

**Comment by bloff** [comment]
It also happens when I'm trying to save to the Downloads folder. Any other specific folder you wish I should try?

I have two computers running timimi, both on Arch linux on Firefox, both with the same directory structure. One of them works, one of them doesn't.

Any idea of what I might do?

**Comment by harmlessdrudge** [comment]
Similar experience here. I'm running Linux Mint 19.3 w Cinnamon desktop and Firefox 80 (64bit) with Timimi installed (v2.1.**3** -- a version that doesn't appear on Github; it would be good have release and installation version numbers synced), w TiddlyWiki v5.1.19. It works ok for me on my laptop. 

Doesn't work on my wife's, running Linux Mint 20 w same desktop and browser, w slightly different version of TiddlyWiki: v5.1.17.

Now trying to work out what's different:

My Timimi is showing it was last updated on 20 August; wife's was on 6 Sept. Both are showing the same version nr v.2.1.3.

I now use a folder called wiki in my home directory; wife was using the same but in Downloads folder and I had tried to copy it to her home folder. However, saving elicits, first this error message (above) then, on proceeding, an indication that the TW has been saved in a "new location" -- reverting to the Downloads/wiki folder. Despite showing the same version number the Timimi extensions installed aren't the same. In addition to the date difference mine shows "Release Notes"; wife's does not. Tried with a new blank TW v5.1.22 on her computer ; no change. Copied a TW I use and which saves OK on mine to my wife's computer and tried to edit and save: no go; same problem; can only save to a new location.

At a glance it looked as if perhaps something might have changed between 20 August and 6 September in Timimi & w no version nr update, but despite the "Release Notes" difference it turns out both copies of the extension were installed from identical files (same SHA256 hash anyway). I'm scratching my head wondering what to try next. Timimi has been by some margin the preferred saver here so I hope there's a fix.

**Comment by bloff** [comment]
An added note: on the computer where timimi on firefox does not work, timimi on chromium *does* work just fine. This suggests that it is an issue with the firefox extension, not the client.

**Comment by bloff** [comment]
Ok, stupid thing I just realized. Timimi actually *does save* the file! It will give the above intrusive and annoying error message, but the changes do get saved, apparently! @harmlessdrudge, can you confirm?

**Comment by bloff** [comment]
Ok, just reread the answer. This is exactly the problem. Once I uninstalled the "save tiddlers" extension, it now saves the wiki without any problems.

Wow, what a mess. Thank you for the help.

**Comment by harmlessdrudge** [comment]
Yeah, one of those why didn't I see that right away moments? /eyeroll At least I wasn't alone. Thanks ;-)
